baseURL = "https://romaniukvadim.github.io/car_inventory/"
locale = "uk-ua"
title = "Каталог доступності авто"
theme = "PaperMod"
publishDir = "docs"
defaultContentLanguage = "uk"

[params]
  home_page_content_dir = "posts"
  env = "production"
  description = "Каталог доступності авто - сучасний інвентар"
  ShowShareButtons = true
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true

  [params.profileMode]
    enabled = false
    title = "Каталог авто"
    imageUrl = "#"
    imageTitle = "Профіль"
    subtitle = "🚗 Швидко | ☁️ Прозоро | 🌙 Просто | 📱 Адаптивно"
    buttons = [
      { name = "Каталог", url = "/" },
      { name = "Про нас", url = "/about/" }
    ]

  [params.assets]
    disableHLJS = true

[i18n]
  "breadcrumbs.posts" = "Пости"

[languages.uk]
  weight = 1
  lang = "uk"
  contentDir = "content"
  direction = "ltr"
  label = "Українська"

[outputs]
  home = ["HTML", "RSS", "JSON"]
